version: "3.9"

services:
  traefik:
    image: traefik:v3.5.4
    container_name: traefik
    command:
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.redis.address=:6379"

      # KubernetesCRD provider
      - "--providers.kubernetescrd=true"
      - "--providers.kubernetescrd.endpoint=https://0.0.0.0:6443"
      - "--providers.kubernetescrd.token=eyJhbGciOiJSUzI1NiIsImtpZCI6IllCYjdUMWRxTlctQnpoNElCYV9TUUhBZk05aUJJTXQtUElnNGxxZlpnRWsifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLnZpbmZyYS5rOHMudHIyLnJxYmFuay5uZXQiXSwiZXhwIjo>
      - "--providers.kubernetescrd.namespaces="
      - "--providers.kubernetescrd.certauthfilepath=/certs/ca.crt"
      - "--serverstransport.rootcas=/certs/ca.crt"

      # Dashboard for debug
      - "--api.insecure=true"
      - "--entrypoints.traefik.address=:8080"

      - "--tracing=true"
      - "--accesslog=true"
    volumes:
      - ./ca.crt:/certs/ca.crt:ro
    ports:
      - "80:80"
      - "443:443"
      - "6379:6379"
      - "8080:8080"
    restart: unless-stopped